# 应用服务 WEB 访问端口
server:
  port: 9090
  # 将Cookie保存的SessionID名称设置为JSEESIONID
  servlet:
    session:
      cookie:
        name: JSESSIONID

spring:
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    timeout: 10m
    store-type: redis
  redis:
    database: 0
    port: 6379

  # 连接数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bkms
    username: root
    password: 123456
#  jackson:
    # 定制Java对象序列化时的日期格式化
#    date-format: yyyy-MM-dd

mybatis:
  # Mapper驼峰扫描
  mapper-locations: mapper/*.xml
  configuration:
    # 数据库字段驼峰转换
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  header: Authorization
  secret: springkhbd
  expiration: 360